# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a460f2681122d732565da006c9abaf1508c6e710d231a4f1aeeb186013bb61406ac13ef6403261c2ef914a3ec3b8d41af9bfe39d6ad3522d41cb151644b77728

test:
  secret_key_base: 9755ce4d35e1fa0ba10fe73d46ebc74cf8db337fe8bf6af094c71013a719cf415b78ea3daa3d3084ee843050afb843cec5bbb07110ee1e74daffb85dd9eb3a23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
